.github/workflows/build-ci.yml, .github/workflows/testing.yml, docker/Dockerfile, docker/docker-compose.yml, docker/entrypoint.sh, lib/api/cln/cln_client.dart, lib/model/app_model/list_funds.dart, lib/views/home/home_view.dart, test/grpc_client_appapi_test.dart, test/widget_test.dart
=> ci: add integration testing

.github/workflows/build-ci.yml, .github/workflows/gh_pages.yml
With this we can release the app on Github action
=> ci: build web version on Github pages

.github/workflows/build-binary.yml, Makefile, pubspec.yaml, test/grpc_client_appapi_test.dart
Fixes https://github.com/dart-lightning/lndart.clnapp/issues/47
=> ci: build and release the binary inside the CI

lib/api/cln/cln_client.dart, lib/main.dart, lib/model/app_model/get_info.dart, lib/model/app_model/list_funds.dart, lib/views/home/home_view.dart, test/unix_client_appapi_test.dart
Fixes https://github.com/dart-lightning/lndart.clnapp/issues/52
Fixes https://github.com/dart-lightning/lndart.clnapp/issues/51
=> fix: fix android support

README.md, changelog.json, docs/dev/MAINTAINERS.md
=> adding docs to clnapp

CHANGELOG.md, changelog.json, pubspec.yaml
=> docs: prepare v0.0.1-alpa.2

lib/api/client_provider.dart, pubspec.yaml
=> fix: fix the url bug by parse the string before

CHANGELOG.md, changelog.json, pubspec.yaml
=> docs: release alpha 3

README.md, ios/Flutter/AppFrameworkInfo.plist, ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcworkspace/contents.xcworkspacedata, lib/components/buttons.dart
Proposed solution to [issue #64 - App does not build for iOS](https://github.com/dart-lightning/lndart.clnapp/issues/64).
Fixes https://github.com/dart-lightning/lndart.clnapp/issues/64
=> ios: fix build

.github/workflows/build-binary.yml
=> Remove enforcing flutter version in subosito/flutter-action@v2

Makefile, lib/views/app_view.dart, lib/views/home/home_view.dart
=> fix: upgrate to the last flutter version

lib/api/client_provider.dart, lib/utils/directory_picker.dart, lib/views/setting/grpc_setting_view.dart, lib/views/setting/lnlambda_setting_view.dart, lib/views/setting/setting_view.dart, lib/views/setting/unix_setting_view.dart, macos/Flutter/GeneratedPluginRegistrant.swift
Created seperate files for different views in the `settings_view.dart` namely
`lib/views/setting/grpc_settings.dart`
`lib/views/setting/lnlambda.dart`
`lib/views/setting/unix_settings.dart`
Also moved the directory picker function into another file under `lib/utils/directory_picker.dart`
Fixes #45
=> Fix: setting view 

lib/model/app_model/pay_invoice.dart, lib/views/pay/pay_view.dart
fixes the crashing of the app in pay view whenever an invoice is paid.
fix #80
=> fix : msat parsing in pay view

lib/model/app_model/list_send_pays.dart, lib/views/pay/pay_view.dart
Fixes https://github.com/dart-lightning/lndart.clnapp/issues/86
cc @Harshit933
=> Some minors fixes 

lib/model/app_model/pay_invoice.dart
fixes https://github.com/dart-lightning/lndart.clnapp/pull/85#discussion_r1144296906
=> fix : payment preimage parsing.

lib/model/app_model/list_invoices.dart, lib/model/app_model/pay_invoice.dart, lib/views/home/home_view.dart, pubspec.yaml
fix #92 
Added the package to decode the paid bolt11 invoices. 
Also added a fix to the previous paid invoices bug on android.
Attaching the screenshot for the same.
=> fix: bump decode to package

.github/workflows/build-ci.yml, android/build.gradle, pubspec.yaml
This commit bumps the flutter version to support till the flutter 4.0.0
fixes #97
=> fix: bump flutter version

lib/components/error.dart, lib/views/home/home_view.dart, lib/views/home/info_view.dart, lib/views/home/paymentlist_view.dart
Cleaned the code of the app.
1. `home_view.dart` : Made two specific files one for the info view (containing the info of balance about the node) namely `info_view.dart` and the other one for the transactions made from the node namely `paymentlist_view.dart` .
2. Made `error.dart` for logging error on the screen.
3. Added some documentation in the code.
4. Fixed minor widget components.
fix #104
=> fix: code clean up

lib/views/home/home_view.dart, lib/views/setting/setting_view.dart, pubspec.yaml
1. In `home_view.dart` and `settings.dart`, all the error shows in a dialog box from the package trash.
=> fix: showing errors in a dialog.

lib/api/api.dart, lib/api/cln/cln_client.dart, lib/api/cln/request/decodeinvoice_request.dart, lib/api/cln/request/listpeers_request.dart, lib/components/bottomsheet.dart, lib/model/app_model/decode_invoice.dart, lib/model/app_model/list_peers.dart, lib/views/pay/numberpad_view.dart, lib/views/pay/pay_view.dart
1. Changes made in `api.dart`, `cln_client.dart`, `decodeinvoice_request.dart`, `decode_invoices.dart` is to implement the functionality of the decode method.
2. Added the `NumberPad.dart` for paying the invoices which have `any` amount associated with them.
3. Updated the `pay view` as per discussion.
=> feat(pay view) : modifies the pay view and implements the decode invoice method

lib/model/app_model/list_invoices.dart, lib/views/home/paymentlist_view.dart
- resolves the bug of 0.0 msats for invoices paid with "any" amount.
- limits the size of the expandable card for bigger screens.
=> fix : changes minor UI elements

lib/api/api.dart, lib/api/cln/cln_client.dart, lib/api/cln/request/newaddr_request.dart, lib/api/cln/request/withdraw_request.dart, lib/model/app_model/newaddr.dart, lib/model/app_model/withdraw.dart, lib/utils/app_utils.dart, lib/views/home/info_view.dart, lib/views/pay/numberpad_view.dart, lib/views/pay/pay_view.dart, lib/views/request/request_view.dart
For now the apps doesn't support btc wallet transactions.
1. Added the functionality to generate a wallet address by using the `newaddr` method to get payments to their wallets.
2. Added the functionality to send btc to wallet address by using the `withdraw` method.
=> fix: adds btc pay support

lib/model/app_model/withdraw.dart, lib/views/pay/numberpad_view.dart
This commit changes tx(hex) of the bitcoin transaction to the txid(transaction id of the signed transaction).
=> fix : changes tx to txid
